language: go

matrix:
  include:
  - go: "1.10.x"
    install: go get -v -t ./...
    script: go test -v ./...
  - go: "1.11.x"
    script: go test -v ./...
  - go: "1.12.x"
    script: go test -v ./...
  - go: "tip"
    script: go test -v ./...

install: true

env:
  - GO111MODULE=on
